from marshmallow import Schema, fields, validate

class TripSchema(Schema):
    document_number = fields.Integer(allow_none=True)
    origin = fields.String(required=True, validate=validate.Length(max=50))
    destination = fields.String(required=True, validate=validate.Length(max=50))
    estimated_kms = fields.Float(allow_none=True, validate=validate.Range(min=0))
    start_date = fields.Date(required=True)
    end_date = fields.Date(allow_none=True)
    load_weight_on_load = fields.Float(allow_none=True, validate=validate.Range(min=0))
    load_weight_on_unload = fields.Float(allow_none=True, validate=validate.Range(min=0))
    rate_per_ton = fields.Float(allow_none=True, validate=validate.Range(min=0))
    fuel_on_client = fields.Boolean(allow_none=True)
    client_advance_payment = fields.Float(allow_none=True, validate=validate.Range(min=0))
    state_id = fields.String(required=True, validate=validate.OneOf(['Pendiente', 'En curso', 'Finalizado']))
    driver_id = fields.Integer(required=True)
    client_id = fields.Integer(required=True)
    load_owner_id = fields.Integer(required=True)

class TripUpdateSchema(Schema):
    document_number = fields.Integer(allow_none=True)
    origin = fields.String(validate=validate.Length(max=50))
    destination = fields.String(validate=validate.Length(max=50))
    estimated_kms = fields.Float(allow_none=True, validate=validate.Range(min=0))
    start_date = fields.Date()
    end_date = fields.Date(allow_none=True)
    load_weight_on_load = fields.Float(allow_none=True, validate=validate.Range(min=0))
    load_weight_on_unload = fields.Float(allow_none=True, validate=validate.Range(min=0))
    rate_per_ton = fields.Float(allow_none=True, validate=validate.Range(min=0))
    fuel_on_client = fields.Boolean(allow_none=True)
    client_advance_payment = fields.Float(allow_none=True, validate=validate.Range(min=0))
    state_id = fields.String(validate=validate.OneOf(['Pendiente', 'En curso', 'Finalizado']))
    driver_id = fields.Integer()
    client_id = fields.Integer()
    load_owner_id = fields.Integer()